ARG BASE_IMAGE=alpine
FROM ${BASE_IMAGE}
ARG TARGETARCH
ARG TARGETVARIANT
LABEL maintainer="flyzstu <flyzstu@gmail.com>"
LABEL org.opencontainers.image.title="xhttp-box"
LABEL org.opencontainers.image.source="https://github.com/flyzstu/xhttp-box"
RUN set -ex \
    && if command -v apk > /dev/null; then \
        apk add --no-cache --upgrade bash tzdata ca-certificates nftables; \
    else \
        apt-get update && apt-get install -y --no-install-recommends bash tzdata ca-certificates nftables \
        && rm -rf /var/lib/apt/lists/*; \
    fi
COPY xhttp-box-${TARGETARCH}${TARGETVARIANT} /usr/local/bin/xhttp-box
ENTRYPOINT ["xhttp-box"]
